""" 
Django settings for solarterra project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import sys
import json

os.environ['OPENBLAS_NUM_THREADS'] = '1'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CONFIG_PATH = os.path.abspath(os.path.join(
    BASE_DIR, '..', 'configs/settings_sensitive.json'))
with open(CONFIG_PATH) as config_file:
    config = json.load(config_file)


SUB_PATH = os.path.abspath(os.path.join(
    BASE_DIR, '..', 'solarterra_submodules'))
MODEL_DIR_PATH = os.path.join(SUB_PATH, 'data_cdf/models')

sys.path.append(SUB_PATH)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['S_K']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

LOG_FILE = os.path.abspath(os.path.join(
    BASE_DIR, '..', 'solarterra_submodules/logs/logfile'))

COLLISIONS_LOGS = os.path.abspath(os.path.join(
    BASE_DIR, '..', 'solarterra_submodules/logs/collisions'))

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.25.107.101']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'data_cdf',
    'load_cdf',
    'pages',
    # Joe's addition for debugging purposes, remove at merge/install django-extentions with pip
    #"django_extensions",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'solarterra.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

WSGI_APPLICATION = 'solarterra.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config['DB_NAME'],
        'USER': config['DB_USER'],
        'PASSWORD': config['DB_PASS'],
        'HOST': config['DB_HOST'],
        'PORT': config['DB_PORT'],
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.abspath(os.path.join(
    BASE_DIR, '..', 'solarterra_submodules/static/'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PROJECT_VERSION = 'v1.1'

# Логирование SQL-запросов Django (django.db.backends)
# ----------------------------------------------------
# Этот раздел включает подробные логи SQL-запросов — полезно для диагностики
# медленных страниц и избыточных запросов (N+1). По умолчанию вывод идет
# только в режиме DEBUG.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # не отключаем стандартные логгеры Django
    # Форматы сообщений: можно быстро переключить на 'verbose'
    'formatters': {
        'simple': {
            # %(name)s — имя логгера (здесь 'django.db.backends'),
            # %(levelname)s — уровень, %(message)s — сам текст (SQL + время)
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
        'verbose': {
            # Добавляет PID/поток — удобно при многопроцессной работе gunicorn/uwsgi
            'format': '%(asctime)s [%(levelname)s] [pid:%(process)d] [thr:%(threadName)s] %(name)s: %(message)s',
        },
    },
    'filters': {
        # Логировать только когда DEBUG = True.
        # Чтобы включить в продакшене — уберите этот фильтр у нужных handlers.
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        # Вывод в консоль (runserver или stdout контейнера)
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        # Ротационный файл (см. переменную LOG_FILE выше)
        # Меняет файл по достижении размера, хранит несколько резервных копий.
        'db_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_FILE,
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
            'formatter': 'simple',
            'filters': ['require_debug_true'],
            # Примечание: убедитесь, что каталог для LOG_FILE существует и доступен на запись.
        },
    },
    'loggers': {
        # Основной логгер SQL-запросов ORM. Уровень DEBUG печатает
        # сам запрос, параметры и длительность выполнения.
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console', 'db_file'],
            'propagate': False,  # не пускать дальше во "внешние" логгеры, чтобы не дублировать
        },
        # При необходимости можно отдельно включать:
        # 'django.db.backends.schema': {'level': 'DEBUG', 'handlers': ['console'], 'propagate': False},
        # 'django.db.backends.transaction': {'level': 'DEBUG', 'handlers': ['console'], 'propagate': False},
    },
}

# Подсказки по использованию:
# - В проде обычно оставляют DEBUG=False и не включают этот логгер
#   (или подключают временно для диагностики, убрав фильтр require_debug_true).
# - Можно точечно форсировать вывод SQL даже при DEBUG=False:
#     from django.db import connection
#     connection.force_debug_cursor = True
#   Делайте это только локально/временно, иначе возможна деградация производительности.